pipeline {

 agent any

 stages {

 stage('Clone Repo') {
 steps {
 git 'https://github.com/username/cloudforge-devops-platform'
 }
 }

 stage('Build Docker Image') {
 steps {
 sh 'docker build -t cloudforge-app .'
 }
 }

 stage('Push Image') {
 steps {
 sh 'docker push dockerhub/cloudforge-app'
 }
 }

 stage('Deploy to Kubernetes') {
 steps {
 sh 'kubectl apply -f kubernetes/'
 }
 }

 }

}